### ISSUE TITLE
FoV & Jitter Bug

### ISSUE THREAD

**Issue by JebLab** [JebLab/mazegame#1]
1. Wide FoV creating visual stretching bugs, recommending changing FoV to 60 as opposed to 120.
2. PlayerLook script is grabbing raw mouse input, need to implement mouse smoothing to remove jitter issues. Putting link to dev describing how he does it + script:
[https://forum.unity.com/threads/a-free-simple-smooth-mouselook.73117/](url)

**Comment by J-SQRD-Dev** [comment]
Please check to see if it's been fixed I realize the fov was set to vertical instead of horizontal so I fixed it and I changed the input system to update dynamically instead of fixed

**Comment by JebLab** [comment]
Issues seem to be fixed, nice work!
